### ISSUE TITLE
Uncaught TypeError: Cannot read property 'prototype' of undefined

### ISSUE THREAD

**Issue by deemx** [ponychicken/atom-paper.js#5]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.7
**System**: Ubuntu 15.04
**Thrown From**: [atom-paperjs](https://github.com/ponychicken/atom-paper.js) package, v0.4.1
### Stack Trace

Uncaught TypeError: Cannot read property 'prototype' of undefined

```
At /home/dee/.atom/packages/atom-paperjs/lib/paperjs-view.coffee:4

TypeError: Cannot read property 'prototype' of undefined
  at __extends (/home/dee/.atom/packages/atom-paperjs/lib/paperjs-view.coffee:1:1)
  at /home/dee/.atom/packages/atom-paperjs/lib/paperjs-view.coffee:11:3
  at Object.<anonymous> (/home/dee/.atom/packages/atom-paperjs/lib/paperjs-view.coffee:299:5)
  at Object.<anonymous> (/home/dee/.atom/packages/atom-paperjs/lib/paperjs-view.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (/home/dee/.atom/packages/atom-paperjs/lib/paperjs.coffee:3:15)
  at Object.<anonymous> (/home/dee/.atom/packages/atom-paperjs/lib/paperjs.coffee:1:1)
  at Module._compile (module.js:452:26)
  at Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:759:34)
  at Package.module.exports.Package.activateConfig (/usr/share/atom/resources/app.asar/src/package.js:261:14)
  at PackageDetailView.module.exports.PackageDetailView.activateConfig (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:212:26)
  at PackageDetailView.module.exports.PackageDetailView.completeInitialzation (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:156:12)
  at PackageDetailView.module.exports.PackageDetailView.loadPackage (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:168:21)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-detail-view.js:298:17
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at PackageManager.module.exports.PackageManager.emitPackageEvent (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:587:27)
  at /usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:378:26
  at exit (/usr/share/atom/resources/app.asar/node_modules/settings-view/lib/package-manager.js:59:16)
  at triggerExitCallback (/usr/share/atom/resources/app.asar/src/buffered-process.js:213:47)
  at ChildProcess.<anonymous> (/usr/share/atom/resources/app.asar/src/buffered-process.js:235:18)
  at emitTwo (events.js:87:13)
  at ChildProcess.emit (events.js:169:7)
  at Process.ChildProcess._handle.onexit (child_process.js:1057:12)

```
### Commands

```
  5x -4:15.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -3:53.7.0 application:open-file (ul.list-inline.tab-bar.inset-panel)
     -2:45.3.0 window:increase-font-size (ul.list-inline.tab-bar.inset-panel)
     -2:43.8.0 window:decrease-font-size (ul.list-inline.tab-bar.inset-panel)
  2x -2:40.8.0 settings-view:open (ul.list-inline.tab-bar.inset-panel)
     -1:18.1.0 core:move-down (div.settings-view.pane-item)
  2x -1:16.6.0 core:move-left (div.settings-view.pane-item)
  2x -1:16 core:move-down (div.settings-view.pane-item)
     -1:14.7.0 core:move-up (button.btn.btn-default.icon.icon-link-external)
     -0:58.7.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "themes": [
      "atom-dark-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
color-picker, v2.0.11
java-importer, v1.3.6
linter-javac, v1.1.0

# Dev
No dev packages
```

**Comment by bugeats** [comment]
I just got this on a fresh install of Atom 1.16.0 with no other plugins. 

Is this project abandoned?
